name: Daily LeetCode Upload

on:
  schedule:
    - cron: '30 23 * * *'  # Runs daily at 11:30 PM

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Add new LeetCode solutions
      run: |
        git config --global user.name 'pooja180795'
        git config --global user.email 'poojachothani.187@gmail.com'
        if [ -d "Leet-Code" ]; then
          cd Leet-Code
          git add .
          git commit -m "Daily update with new LeetCode solutions" || echo "No changes to commit"
          git push origin main || echo "No changes to push"
        else
          echo "Directory Leet-Code does not exist"


    - name: Push changes
      run: |
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
